### ISSUE TITLE
A way to select which model?

### ISSUE THREAD

**Issue by chookity-pokk** [emacs-openai/openai#1]
I tried looking around in the code and think that running `openai-retrieve-model` let's you select which model to use? I'm not totally sure though. If that is correct I can open a PR with that info in the README.

**Comment by jcs090218** [comment]
I think you are referring to `openai-completion.el`? See 

https://github.com/emacs-openai/openai/blob/2310f983081205fcab0b167c8e89913d69c0d9e8/openai-completion.el#L31

You can set it by doing:

```elisp
(setq openai-completon-model "MODEL-NAME")
```
