### ISSUE TITLE
Adding organization to request

### ISSUE THREAD

**Issue by rommeswi** [emacs-openai/openai#12]
According to [this documentation](https://platform.openai.com/docs/api-reference/authentication), an organization can be provided in case of multiple organizations.

Also, it seems that the user does not need to be specified, only the key.

**Comment by jcs090218** [comment]
Implemented in #13, the key is `org-id`.

> Also, it seems that the user does not need to be specified, only the key.

I think `user` are only optional. The main goal of this package is to share the same variables across all OpenAI-related packages, like `openai-key`, etc. `openai-user` is specified since this could benefit the user, and it follows this principle.
