### ISSUE TITLE
Usernames with special characters generate a 400 error

### ISSUE THREAD

**Issue by rommeswi** [emacs-openai/openai#17]
How to reproduce:
- Set username to be your email address, including an @ 
- Running chatgpt or dall-e or anything interactive will yield an error.
- Observe that it is not clear from the error that there is a problem with the username.

Expected behavior:
It would probably be best to see an informative error message if one uses a username that is disallowed.

**Comment by jcs090218** [comment]
Can you try our debug section, see https://github.com/emacs-openai/openai#-debugging.

It should print out the reason message for the failed request.

**Comment by rommeswi** [comment]
Great, that helps! I think a reference to (setq openai--show-log t) in the 400 error would be useful, though.
