### ISSUE TITLE
Add option for api-key header for azure openai deployment

### ISSUE THREAD

**Issue by lilactown** [emacs-openai/openai#22]
#16 allows you to use bearer tokens with azure openai, but I would like to use a long lived token that Azure provides. These tokens are not normal bearer tokens that are passed via the `Authorization` header, but are instead passed via an `api-key` header.

Allowing this to be configured (global config and/or per-request) would be helpful.

**Comment by jcs090218** [comment]
That's a good idea! Would you like to open a PR for this? 🤔

**Comment by lilactown** [comment]
I could, but I'm not very good at elisp. I'll open a PR for feedback!
